var dataAcc=[
  {"id":"00",
   "mk":"00",
   "name":"Cuongbokdeptrai",
   "ref":"01",
   "refBy":"",
  },
  {"id":"01",
   "mk":"VINH0399173413",
   "name":"Trần Công Vinh",
   "ref":"",
   "refBy":"",
  },
  {"id":"02",
   "mk":"null",
   "name":"QuynhAnh",
   "ref":"",
   "refBy":"",
  },
  {"id":"03",
   "mk":"matkhaumoi12",
   "name":"Nguyen Hai",
   "ref":"",
   "refBy":"",
  },
]
